### ISSUE TITLE
Lua chunk error 

### ISSUE THREAD

**Issue by ElAouane** [awesome-streamers/awesome-streamerrc#24]
Hello guys. I am trying to install Melkey vim config. But when I run the PlugInstall, everything get installed but then I get this error: `E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: loop or previous error loading module 'completion'`

Any idea why is this error pops up?

**Comment by Amokstakov** [comment]
@ElAouane try now! I updated my configs
