### ISSUE TITLE
Have you tried coc-fzf?

### ISSUE THREAD

**Issue by antoinemadec** [awesome-streamers/awesome-streamerrc#3]
Really like your config and your workflow.
I am rather bias because i am the maintainer, but i really think you would love ```coc-fzf```.

It replaces all the CocList with Fzf.
You now use your ```ctrl-t```, muti-select, file preview, floating window etc.

Cheers!
Antoine

**Comment by lucax88x** [comment]
+that

Amazing library.

**Comment by erkrnt** [comment]
Appreciate the suggestion!

I believe both @ThePrimeagen and I are now using NVIM's built-in LSP support with these plugins and have good results so far: 

```" Neovim lsp Plugins
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
Plug 'tjdevries/nlua.nvim'
Plug 'tjdevries/lsp_extensions.nvim'

Might be worth taking a look at too!
