### ISSUE TITLE
Coc Extensions List

### ISSUE THREAD

**Issue by cxgslegend** [awesome-streamers/awesome-streamerrc#6]
I was just curious if there was a reason you didn't list your coc extensions with `g:coc_global_extensions`?

Here is mine:
```
let g:coc_global_extensions=[
\	'coc-clangd',
\	'coc-css',
\	'coc-html',
\	'coc-json',
\	'coc-markdownlint',
\	'coc-phpls',
\	'coc-python',
\	'coc-r-lsp',
\	'coc-sql',
\	'coc-texlab',
\	'coc-tsserver',
\	'coc-vetur',
\	'coc-vimlsp',
\	'coc-xml',
\	'coc-yaml',
\]
```

If you are not familiar with it, it will automatically install any of the missing extensions when you start neovim.

**Comment by erkrnt** [comment]
Great suggestion - I went ahead and updated mine in this commit 32e3845f82a30f5fdf3b70728352adba20bf3e75
